# Register indices.
DEF REG_A  = 0x0
DEF REG_B  = 0x1
DEF REG_C  = 0x2
DEF REG_X  = 0x3
DEF REG_Y  = 0x4
DEF REG_Z  = 0x5
DEF REG_I  = 0x6
DEF REG_J  = 0x7
DEF REG_SP = 0x8
DEF REG_PC = 0x9
DEF REG_O  = 0xA

DEF STACK_POP = 0
DEF STACK_PEEK = 1
DEF STACK_PUSH = 2
